parameters:
  session.storage.options:
    gc_probability: 1
    gc_divisor: 100
    gc_maxlifetime: 200000
    cookie_lifetime: 2000000
    sid_length: 48
    sid_bits_per_character: 6
  twig.config:
    debug: false
    auto_reload: null
    cache: true
  renderer.config:
    required_cache_contexts:
      - 'languages:language_interface'
      - theme
      - user.permissions
    auto_placeholder_conditions:
      max-age: 0
      contexts:
        - session
        - user
      tags: {  }
  http.response.debug_cacheability_headers: true
  factory.keyvalue: {  }
  factory.keyvalue.expirable: {  }
  filter_protocols:
    - http
    - https
    - ftp
    - news
    - nntp
    - tel
    - telnet
    - mailto
    - irc
    - ssh
    - sftp
    - webcal
    - rtsp
  cors.config:
    enabled: false
    allowedHeaders: {  }
    allowedMethods: {  }
    allowedOrigins:
      - '*'
    exposedHeaders: false
    maxAge: false
    supportsCredentials: false
services:
  testing.config_schema_checker:
    class: Drupal\Core\Config\Development\ConfigSchemaChecker
    arguments:
      - '@config.typed'
      -
        - config_schema_test.noschema
        - config_schema_test.someschema
        - config_schema_test.schema_data_types
        - config_schema_test.no_schema_data_types
        - config_test.dynamic.system
    tags:
      -
        name: event_subscriber
