version: '3.6'
#ddev-generated
services:

  db:
    container_name: ddev-${DDEV_SITENAME}-db
    build:
      context: '/home/josh/myprojects/ddev-vscode-devcontainer-drupal9-template/.ddev/db-build'
      dockerfile: '/home/josh/myprojects/ddev-vscode-devcontainer-drupal9-template/.ddev/.dbimageBuild/Dockerfile'
      args:
        BASE_IMAGE: $DDEV_DBIMAGE
        username: 'josh'
        uid: '1000'
        gid: '1000'
    image: ${DDEV_DBIMAGE}-${DDEV_SITENAME}-built
    stop_grace_period: 60s
    volumes:
      - type: "volume"
        source: mariadb-database
        target: "/var/lib/mysql"
        volume:
          nocopy: true
      - type: "bind"
        source: "."
        target: "/mnt/ddev_config"
      - ddev-global-cache:/mnt/ddev-global-cache
    restart: "no"
    user: "$DDEV_UID:$DDEV_GID"
    hostname: ddev-vscode-devcontainer-drupal9-template-db
    ports:
      - "127.0.0.1:$DDEV_HOST_DB_PORT:3306"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: drupal9
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - COLUMNS
      - DDEV_HOSTNAME
      - DDEV_PHP_VERSION
      - DDEV_PRIMARY_URL
      - DDEV_PROJECT
      - DDEV_PROJECT_TYPE
      - DDEV_ROUTER_HTTP_PORT
      - DDEV_ROUTER_HTTPS_PORT
      - DDEV_SITENAME
      - DDEV_TLD
      - DOCKER_IP=127.0.0.1
      - HOST_DOCKER_INTERNAL_IP=
      - IS_DDEV_PROJECT=true
      - LINES
      - TZ=Europe/Berlin
    command: "$DDEV_MARIADB_LOCAL_COMMAND"
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 120s
      timeout: 120s

  web:
    container_name: ddev-${DDEV_SITENAME}-web
    build:
      context: '/home/josh/myprojects/ddev-vscode-devcontainer-drupal9-template/.ddev/web-build'
      dockerfile: '/home/josh/myprojects/ddev-vscode-devcontainer-drupal9-template/.ddev/.webimageBuild/Dockerfile'
      args:
        BASE_IMAGE: $DDEV_WEBIMAGE
        username: 'josh'
        uid: '1000'
        gid: '1000'
    image: ${DDEV_WEBIMAGE}-${DDEV_SITENAME}-built
    cap_add:
      - SYS_PTRACE
    volumes:
      
      - type: bind
        source: ../
        target: /var/www/html
        
        consistency: cached
        
      
      - ".:/mnt/ddev_config:ro"
      - "./nginx_full:/etc/nginx/sites-enabled:ro"
      - "./apache:/etc/apache2/sites-enabled:ro"
      - ddev-global-cache:/mnt/ddev-global-cache
      
      - ddev-ssh-agent_socket_dir:/home/.ssh-agent
      

    restart: "no"
    user: "$DDEV_UID:$DDEV_GID"
    hostname: ddev-vscode-devcontainer-drupal9-template-web
    
    links:
      - db:db
    
    # ports is list of exposed *container* ports
    ports:
      - "127.0.0.1:$DDEV_HOST_WEBSERVER_PORT:80"
      - "127.0.0.1:$DDEV_HOST_HTTPS_PORT:443"
    environment:
      - COLUMNS
      - DOCROOT=${DDEV_DOCROOT}
      - DDEV_DOCROOT
      - DDEV_HOSTNAME
      - DDEV_PHP_VERSION
      - DDEV_PRIMARY_URL
      - DDEV_PROJECT
      - DDEV_PROJECT_TYPE
      - DDEV_ROUTER_HTTP_PORT
      - DDEV_ROUTER_HTTPS_PORT
      - DDEV_SITENAME
      - DDEV_TLD
      - DDEV_FILES_DIR
      - DDEV_WEBSERVER_TYPE
      - DDEV_XDEBUG_ENABLED
      - DEPLOY_NAME=local

      - DRUSH_OPTIONS_URI=$DDEV_PRIMARY_URL

      - DRUSH_ALLOW_XDEBUG=1
      - DOCKER_IP=127.0.0.1
      - HOST_DOCKER_INTERNAL_IP=
      # HTTP_EXPOSE allows for ports accepting HTTP traffic to be accessible from <site>.ddev.site:<port>
      # To expose a container port to a different host port, define the port as hostPort:containerPort
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025
      # You can optionally expose an HTTPS port option for any ports defined in HTTP_EXPOSE.
      # To expose an HTTPS port, define the port as securePort:containerPort.
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025
      - IS_DDEV_PROJECT=true
      - LINES
      - SSH_AUTH_SOCK=/home/.ssh-agent/socket
      - TZ=Europe/Berlin
      - VIRTUAL_HOST=${DDEV_HOSTNAME}
      
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: drupal9
      com.ddev.approot: $DDEV_APPROOT

    external_links:
    - "ddev-router:ddev-vscode-devcontainer-drupal9-template.ddev.site"
    
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 120s
      timeout: 120s


  dba:
    container_name: ddev-${DDEV_SITENAME}-dba
    image: $DDEV_DBAIMAGE
    restart: "no"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: drupal9
      com.ddev.approot: $DDEV_APPROOT
    links:
      - db:db
    ports:
      - "80"
    hostname: ddev-vscode-devcontainer-drupal9-template-dba
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=root
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - UPLOAD_LIMIT=1024M
      - TZ=Europe/Berlin
      # HTTP_EXPOSE allows for ports accepting HTTP traffic to be accessible from <site>.ddev.site:<port>
      - HTTP_EXPOSE=${DDEV_PHPMYADMIN_PORT}:8036
      - HTTPS_EXPOSE=${DDEV_PHPMYADMIN_HTTPS_PORT}:8036
    healthcheck:
      interval: 120s
      timeout: 2s
      retries: 1

networks:
  default:
    external:
      name: ddev_default
volumes:
  
  mariadb-database:
    name: "${DDEV_SITENAME}-mariadb"
  
  
  ddev-ssh-agent_socket_dir:
    external: true
  
  ddev-global-cache:
    name: ddev-global-cache

  

  